# SPDX-FileCopyrightText: 2021 - 2022 Slavi Pantaleev
# SPDX-FileCopyrightText: 2022 Marko Weltzer
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of coturn service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/coturn.service"
  register: coturn_service_stat
  when: "not coturn_enabled | bool"

- when: coturn_service_stat.stat.exists | bool
  block:
    - name: Ensure coturn is stopped
      ansible.builtin.service:
        name: coturn
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure coturn-reload.timer is stopped
      ansible.builtin.service:
        name: coturn
        state: stopped
        enabled: false
        daemon_reload: true
      failed_when: false

    - name: Ensure systemd units don't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ item }}"
        state: absent
      with_items:
        - coturn.service
        - coturn-reload.service
        - coturn-reload.timer

    - name: Ensure Matrix coturn paths don't exist
      ansible.builtin.file:
        path: "{{ coturn_base_path }}"
        state: absent
